### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FallenRiteMonk** [zenkkor/ngx-cookies#4]
I get the following error:
```
ERROR in ./node_modules/ngx-cookies/index.ts
Module build failed: Error: <PROJECT_PATH>/node_modules/ngx-cookies/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/<PROJECT_PATH>/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (<PROJECT_PATH>/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./libs/api/src/+state/auth.init.ts 3:20-42
 @ ./libs/api/src/api.module.ts
 @ ./libs/api/index.ts
 @ ./libs/auth/src/auth.module.ts
 @ ./apps/admin/src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./apps/admin/src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./apps/admin/src/main.ts
```

ng --version:
```
Angular CLI: 1.6.5
Node: 8.9.4
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.3.1
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by kasskata** [comment]
I have same issue. Do we have workaround ?

**Comment by abhishekbadola** [comment]
I got the same issue, :(
Any resolution to this?

\node_modules\ngx-cookies\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
